######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 7 17:17:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += HelloForm.h
FORMS += HelloForm.ui
SOURCES += HelloForm.cpp main.cpp
